const products = [
    {
        id: 1,
        name: "Portable Bluetooth Speaker",
        categories: "AUDIO",
        price: 129.99,
        rating: 3.5,
        reviews: "Based on 327 reviews",
        image: "images/picture-one.jpg",
        KeyHighlights: {
            OutputPower: "20W",
            BatteryLife: "15 hours",
            WaterRating: "IPX7",
        },
        specifications: {
            OutputPower: "20W",
            BatteryLife: "15 hours",
            WaterRating: "IPX7",
            Bluetooth: "5.2",
            Range: "30 meters",
            Charging: "USB-C",
        },
        description: "Take your music anywhere with this powerful portable speaker. Delivers rich, immersive sound with deep bass. Waterproof design perfect for outdoor adventures and pool parties."
    },

    {
        id: 2,
        name: "Premium Wireless Headphones",
        categories: "AUDIO",
        price: 299.99,
        oldPrice: 374.99,
        rating: 5,
        reviews: "Based on 327 reviews",
        image: "images/picture-two.jpg",
        KeyHighlights: {
            BatteryLife: "40 hours",
            Connectivity: "Bluetooth 5.3",
            NoiseCancellation: "Active ANC",
        },
        specifications: {
            BatteryLife: "40 hours",
            Connectivity: "Bluetooth 5.3",
            NoiseCancellation: "Active ANC",
            DriverSize: "40mm",
            Weight: "250g",
            ChargingTime: "2 hours",
        },
        description: "Experience immersive audio with our premium wireless headphones. Featuring advanced noise cancellation, 40-hour battery life, and studio-quality sound. Perfect for music enthusiasts and professionals who demand the best audio experience.",
    },

    {
        id: 3,
        name: "Professional DSLR Camera",
        categories: "PHOTOGRAPHY",
        price: 2499.99,
        oldPrice: 3125.99,
        rating: 5,
        reviews: "Based on 327 reviews",
        image: "images/picture-three.jpg",
        KeyHighlights: {
            Sensor: "45MP Full-Frame",
            Video: "4K 60fps",
            ISORange: "100-51200",
        },
        specifications: {
            Sensor: "45MP Full-Frame",
            Video: "4K 60fps",
            ISORange: "100-51200",
            AutofocusPoints: "693",
            BurstSpeed: "10 fps",
            Display: '3.2" Tilting Touchscreen',
        },
        description: "Capture stunning images with this professional-grade DSLR camera. Features a full-frame sensor, 4K video recording, and exceptional low-light performance. Perfect for serious photographers and videographers.",
    },

    {
        id: 4,
        name: "Professional Laptop Pro",
        categories: "COMPUTERS",
        price: 1899.99,
        oldPrice: 2373.99,
        rating: 4.5,
        reviews: "Based on 327 reviews",
        image: "images/picture-four.jpg",
        KeyHighlights: {
            Processor: "Intel Core i9",
            RAM: "32GB DDR5",
            Storage: "1TB SSD",
        },
        specifications: {
            Processor: "Intel Core i9",
            RAM: "32GB DDR5",
            Storage: "1TB SSD",
            Display: '15.6" 4K OLED',
            Graphics: "NVIDIA RTX 4060",
            Battery: "12 hours",
        },
        description: "Powerful performance meets sleek design in this professional laptop. Equipped with the latest processor, stunning display, and all-day battery life. Ideal for creative professionals and power users.",
    },

    {
        id: 5,
        name: "Smart Fitness Watch Ultra",
        categories: "WEARABLES",
        price: 449.99,
        oldPrice: 561.99,
        rating: 4,
        reviews: "Based on 327 reviews",
        image: "images/picture-five.jpg",
        KeyHighlights: {
            Display: '1.9" AMOLED',
            BatteryLife: "7 days",
            WaterResistance: "50m",
        },
        specifications: {
            Display: '1.9" AMOLED',
            BatteryLife: "7 days",
            WaterResistance: "50m",
            GPS: "Built-in",
            HealthSensors: "Heart Rate, SpO2, ECG",
            Compatibility: "iOS & Android",
        },
        description: "Track your fitness goals with precision and style. Features advanced health monitoring, GPS tracking, and a vibrant always-on display. Water-resistant and built for active lifestyles.",
    },

    {
        id: 6,
        name: "Ultra-Thin Tablet Pro",
        categories: "TABLETS",
        price: 799.99,
        rating: 4.5,
        reviews: "Based on 327 reviews",
        image: "images/picture-six.jpg",
        KeyHighlights: {
            Display: '12.9" Liquid Retina',
            Processor: "M2 Chip",
            Storage: "256GB",
        },
        specifications: {
            Display: '12.9" Liquid Retina',
            Processor: "M2 Chip",
            Storage: "256GB",
            RAM: "8GB",
            Battery: "10 hours",
            StylusSupport: "Yes",
        },
        description: "Experience productivity and entertainment on a stunning display. This ultra-thin tablet features powerful performance, all-day battery, and support for stylus input. Perfect for work and play.",
    },
];

console.log("Товары:", products);